name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, macos-14, macos-15-intel, ubuntu-24.04, ubuntu-22.04]
        cache: [true, false]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Homebrew
        if: runner.os != 'macOS'
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install possibly existing formula
        uses: ./
        with:
          packages: python
          cache: ${{ matrix.cache }}
      - name: Install new formula
        uses: ./
        with:
          packages: open-mpi
          cache: ${{ matrix.cache }}
      - name: Install cask
        if: runner.os == 'macOS'
        uses: ./
        with:
          packages: vv
          type: cask
          cache: ${{ matrix.cache }}
